apiVersion: apps/v1
kind: Deployment
metadata:
  name: pace
spec:
  template:
    spec:
      initContainers:
      - name: db-migration
        env:
          - name: NODE_ENV
            value: "dev"
          - name: POSTGRES_HOST
            value: dev-pace-postgresql
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dev-pace-postgresql
      containers:
      - name: pace
        env:
          - name: NODE_ENV
            value: "dev"
          - name: POSTGRES_HOST
            value: dev-pace-postgresql
          - name: REDIS_HOST
            value: dev-redis
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dev-pace-postgresql
