apiVersion: apps/v1
kind: Deployment
metadata:
  name: pace
spec:
  template:
    spec:
      containers:
      - name: pace
        env:
          - name: NODE_ENV
            value: "development"
          - name: POSTGRES_HOST
            value: dev-pace-postgresql
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dev-pace-postgresql
