namePrefix: dev-
namespace: dev-pace
commonLabels:
  variant: development
bases:
- ../base/

resources:
  - ingress.yaml
  - backup.yaml
patchesStrategicMerge:
  - deployment.yaml
  - worker.yaml

secretGenerator:
  - name: pace-secrets
    behavior: merge
    env: dev.env
