apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  template:
    spec:
      containers:
        - name: pace
          env:
            - name: NODE_ENV
              value: "development"
            - name: REDIS_HOST
              value: dev-redis
