redis:
  image: redis
  ports:
    - "6379:6379"
db:
  image: postgres:alpine
  ports:
    - "5432:5432"
  volumes:
    - pace2-db-volume:/var/lib/postgresql/data
  environment:
    - POSTGRES_USER=pace
    - POSTGRES_PASSWORD=pace
    - POSTGRES_DB=pace

