apiVersion: apps/v1
kind: Deployment
metadata:
  name: pace
spec:
  template:
    spec:
      containers:
      - name: pace
        env:
          - name: NODE_ENV
            value: "production"
          - name: POSTGRES_HOST
            value: prod-pace-postgresql
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: prod-pace-postgresql
