apiVersion: apps/v1
kind: Deployment
metadata:
  name: pace
spec:
  replicas: 3
  template:
    spec:
      initContainers:
        - name: db-migration
          env:
            - name: NODE_ENV
              value: "production"
            - name: POSTGRES_HOST
              value: prod-pace-postgresql
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prod-pace-postgresql
      containers:
      - name: pace
        env:
          - name: NODE_ENV
            value: "production"
          - name: REDIS_HOST
            value: prod-redis
          - name: POSTGRES_HOST
            value: prod-pace-postgresql
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: prod-pace-postgresql
