namePrefix: prod-
namespace: prod-pace
commonLabels:
  variant: production
bases:
- ../base/
resources:
  - ingress.yaml
  - backup.yaml
patchesStrategicMerge:
  - deployment.yaml
  - worker.yaml

secretGenerator:
  - name: pace-secrets
    behavior: merge
    env: prod.env
