apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: pace
          env:
            - name: NODE_ENV
              value: "production"
            - name: REDIS_HOST
              value: prod-redis
