apiVersion: apps/v1
kind: Deployment
metadata:
  name: pace
spec:
  replicas: 1
  template:
    metadata:
      labels:
        use: app
    spec:
      initContainers:
        - name: db-migration
          image: localhost:32000/pace2:latest
          command: [ 'sh', '-c', "npx sequelize db:migrate"]
          env:
            - name: NODE_ENV
              value: "local"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_HOST
              value: pace-postgresql
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pace-postgresql
                  key: postgresql-password
      containers:
      - name: pace
        image: localhost:32000/pace2:latest
        ports:
          - containerPort: 3000
        volumeMounts:
          - mountPath: /zip
            name: zip-volume
        env:
          - name: NODE_ENV
            value: "local"
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_HOST
            value: pace-postgresql
          - name: ZIPDIR
            value: '/zip/'
          - name: REDIS_HOST
            value: redis
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pace-postgresql
                key: postgresql-password
          - name: PACE_JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: pace-secrets
                key: token
          - name: PACE_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pace-secrets
                key: password
      volumes:
        - name: zip-volume
          hostPath:
            path: /zip
            type: Directory
