commonLabels:
  app: pace

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pace

resources:
  - service.yaml
  - deployment.yaml
  - namespace.yaml
  - redis.yaml
  - worker.yaml

secretGenerator:
  - name: pace-secrets
    env: secrets.env

configMapGenerator:
  - name: redis-config
    files:
      - redis-config